import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import { SessionProvider } from "next-auth/react";
import { CartProvider } from "@/context/CartContext";
import Main from "@/components/layout/Main";
import { NotificationProvider } from "@/context/NotificationContext";
import { NotificationStack } from "@/components/ui/Notification";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scrollbar-gutter-stable`}
    >
      <body className="flex flex-col w-full max-w-360 mx-auto items-center justify-center">
        <SessionProvider>
          <NotificationProvider>
            <CartProvider>
              <Header />
              <NotificationStack />
              <Main>{children}</Main>
              <Footer />
            </CartProvider>
          </NotificationProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
